// <auto-generated />
using System;
using Execute_storedProcedure_DotnetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Execute_storedProcedure_DotnetCore.Migrations
{
    [DbContext(typeof(MiApiContext))]
    partial class MiApiConextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Actuacion", b =>
                {
                    b.Property<int>("IdActuacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActuacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Presupuesto")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdActuacion");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Actuacion");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Director", b =>
                {
                    b.Property<int>("IdDirector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDirector"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("IdDirector");

                    b.ToTable("Director");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdPais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Poblacion", b =>
                {
                    b.Property<int>("IdPoblacion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdActuacion")
                        .HasColumnType("int");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumHabitantes")
                        .HasColumnType("int");

                    b.Property<int?>("ProyectoIdProyecto")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdPoblacion");

                    b.HasIndex("IdPais")
                        .IsUnique();

                    b.HasIndex("ProyectoIdProyecto");

                    b.ToTable("Poblacion");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("int");

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<int>("Presupuesto")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdProyecto");

                    b.HasIndex("IdResponsable")
                        .IsUnique();

                    b.ToTable("Proyecto");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Responsable", b =>
                {
                    b.Property<int>("IdResponsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResponsable"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("IdResponsable");

                    b.ToTable("Responsable");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSede"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdDirector")
                        .HasColumnType("int");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdSede");

                    b.HasIndex("IdDirector")
                        .IsUnique();

                    b.HasIndex("IdPais")
                        .IsUnique();

                    b.ToTable("Sede");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Actuacion", b =>
                {
                    b.HasOne("Execute_storedProcedure_DotnetCore.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Poblacion", b =>
                {
                    b.HasOne("Execute_storedProcedure_DotnetCore.Models.Pais", "Pais")
                        .WithOne()
                        .HasForeignKey("Execute_storedProcedure_DotnetCore.Models.Poblacion", "IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Execute_storedProcedure_DotnetCore.Models.Actuacion", "Actuacion")
                        .WithMany("Poblaciones")
                        .HasForeignKey("IdPoblacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Execute_storedProcedure_DotnetCore.Models.Proyecto", null)
                        .WithMany("Poblaciones")
                        .HasForeignKey("ProyectoIdProyecto");

                    b.Navigation("Actuacion");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Proyecto", b =>
                {
                    b.HasOne("Execute_storedProcedure_DotnetCore.Models.Sede", "Sede")
                        .WithMany("Proyectos")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Execute_storedProcedure_DotnetCore.Models.Responsable", "Responsable")
                        .WithOne()
                        .HasForeignKey("Execute_storedProcedure_DotnetCore.Models.Proyecto", "IdResponsable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsable");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Sede", b =>
                {
                    b.HasOne("Execute_storedProcedure_DotnetCore.Models.Director", "Director")
                        .WithOne()
                        .HasForeignKey("Execute_storedProcedure_DotnetCore.Models.Sede", "IdDirector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Execute_storedProcedure_DotnetCore.Models.Pais", "Pais")
                        .WithOne()
                        .HasForeignKey("Execute_storedProcedure_DotnetCore.Models.Sede", "IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Actuacion", b =>
                {
                    b.Navigation("Poblaciones");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Proyecto", b =>
                {
                    b.Navigation("Poblaciones");
                });

            modelBuilder.Entity("Execute_storedProcedure_DotnetCore.Models.Sede", b =>
                {
                    b.Navigation("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
